fix url to coc page
data-umbrella/event-board-web pull request #161
Opened 2022-09-11 16:33 UTC by reshamas

## Ticket Description
<-- Copy and paste or write the tickets description here-->

## Description of Changes
On the "Contact Us" page, updated the URL to the CoC page.

## Before and After for UI Updates
 
Before:

After:

## For PR Reviewer
- [ ] Does this file change the yarn.lock, package.json or package-lock.json file? If so, why?
- [ ] If this pr contains mobile and desktop changes, did you test on IphoneXr and desktop views?
- [ ] Does this file match the related tickets linked figma file, or does it pass the visual smell test?
- [ ] If this file contains javascript, does the javascript pass the smell test?
- [ ] If you don't feel super confident in your review, did you assign someone more senior to double check?

2022-09-14 00:55 UTC, jtorreggiani commented on src/components/pages/ContactPage.jsx
> +              <a className={formStyleClasses.hyperlinks} href="/codeofconduct">
@reshamas, we will want to use a React Router Link here.

You just need to update line 9 from 

```JavaScript
import { useNavigate } from 'react-router-dom';
```
to
```JavaScript
import { Link, useNavigate } from 'react-router-dom';
```
and update this line to

```JavaScript
<Link to="/codeofconduct" className={formStyleClasses.hyperlinks}>
  Code of Conduct
</Link>*
```

2022-09-14 00:56 UTC, jtorreggiani requested changes
@reshamas, just one comment to update this. Adding instructions on the fix. Let me know if you have any questions!

2022-09-14 14:57 UTC, reshamas commented
> @reshamas, just one comment to update this. Adding instructions on the fix. Let me know if you have any questions!

Thanks for the review @jtorreggiani.  I submitted the updates.

2022-09-15 03:06 UTC, jtorreggiani approved these changes

2022-09-15 03:11 UTC, jtorreggiani commented
@reshamas, looks like someone updated the same file on main which caused a merge conflict. I fixed the merge conflict for you and are going to merge this in.

2022-09-15 03:12 UTC, jtorreggiani approved these changes
LGTM ✅

2022-09-15 03:16 UTC, merged